// @generated by @bounded-systems/schema-gen — DO NOT EDIT.
// Author the schema (with .describe()) and run your `schema:gen` script.

/**
 * Output from `bd show <id> --json`
 */
export interface BdShowOutput {
  /**
   * Beads record ID
   */
  id: string;
  /**
   * Record title
   */
  title: string;
  /**
   * Record description
   */
  description?: string | null | undefined;
  /**
   * Record status
   */
  status: string;
  /**
   * Record priority level
   */
  priority?: number | null | undefined;
  /**
   * Issue type classification
   */
  issueType?: string | null | undefined;
  /**
   * Associated labels
   */
  labels?: string[] | null | undefined;
  /**
   * IDs of blocking records
   */
  blockedBy?: string[] | null | undefined;
  /**
   * Primary external reference
   */
  externalRef?: string | null | undefined;
  /**
   * Map of external system references
   */
  externalRefs?: {
    [k: string]: string;
  } | null;
  /**
   * Arbitrary metadata map
   */
  metadata?: {
    [k: string]: unknown;
  } | null;
  /**
   * Source system identifier
   */
  sourceSystem?: string | null | undefined;
  /**
   * Last update timestamp
   */
  updatedAt?: string | null | undefined;
}

/**
 * Member of a deduplication cluster
 */
export interface BdDuplicatesClusterMember {
  /**
   * Beads record ID
   */
  beadsId: string;
  /**
   * Record title
   */
  title: string;
  /**
   * Record status
   */
  status: string;
  /**
   * Priority level or null
   */
  priority: number | null;
}

/**
 * Cluster of duplicate records
 */
export interface BdDuplicatesCluster {
  /**
   * Target record to merge into
   */
  target: {
    /**
     * Beads record ID
     */
    beadsId: string;
    /**
     * Record title
     */
    title: string;
    /**
     * Record status
     */
    status: string;
    /**
     * Priority level or null
     */
    priority: number | null;
  };
  /**
   * Records to merge from (minimum 1)
   *
   * @minItems 1
   */
  sources: [
    {
      /**
       * Beads record ID
       */
      beadsId: string;
      /**
       * Record title
       */
      title: string;
      /**
       * Record status
       */
      status: string;
      /**
       * Priority level or null
       */
      priority: number | null;
    },
    ...{
      /**
       * Beads record ID
       */
      beadsId: string;
      /**
       * Record title
       */
      title: string;
      /**
       * Record status
       */
      status: string;
      /**
       * Priority level or null
       */
      priority: number | null;
    }[]
  ];
}

/**
 * Health check issue from `bd doctor`
 */
export interface BdDoctorIssue {
  /**
   * Issue category name
   */
  category: string;
  /**
   * Number of issues
   */
  count: number;
  /**
   * Whether the issue is automatically fixable
   */
  fixable: boolean;
}

/**
 * Health report from `bd doctor --json`
 */
export interface BdDoctorReport {
  /**
   * Total issues found
   */
  total: number;
  /**
   * Number of fixable issues
   */
  fixable: number;
  /**
   * List of detected issues
   */
  issues: {
    /**
     * Issue category name
     */
    category: string;
    /**
     * Number of issues
     */
    count: number;
    /**
     * Whether the issue is automatically fixable
     */
    fixable: boolean;
  }[];
}

/**
 * Result from `bd merge`
 */
export interface BdMergeResultPayload {
  /**
   * Target record ID
   */
  target: string;
  /**
   * Source record IDs merged
   */
  sources: string[];
  /**
   * Whether the merge was applied
   */
  applied: boolean;
}

